### ISSUE TITLE
Solr 5 support

### ISSUE THREAD

**Issue by tisto** [collective/collective.recipe.solrinstance#36]
Solr 5.0.0 is out: http://lucidworks.com/blog/solr-5-0/

It would be great if c.r.solrinstance would support that release at some point.

**Comment by saily** [comment]
Just stumbled over this issue, i'm looking into that and give some details.

**Comment by saily** [comment]
@tisto, this recipe is a huge mess. i'm thinking about rewriting the whole stuff and release a new major `6.0.0` version for Solr5 since they changed directory structure and included scripts. IMHO it should be easier to write a recipe for Solr5.

-  `2.x` for Solr 1.4
- `< 6.0.0` for Solr 3.5, 4.x
- `>= 6.0.0` for Solr 5 and above

What do you think?

**Comment by saily** [comment]
I'd also like to include @jensens opinion, he just did some similar rewrite for `plone.recipe.varnish`

**Comment by saily** [comment]
a basic working alpha implemented. Need to fix/refactor tests.

**Comment by saily** [comment]
While working on the tests for 3 different versions of Solr and dealing around with single-core setups, i stumbled over several problems, so please see #39.
